class BillRunner{

public static void main(String[] args){
	
	
	Bill ref1 = new Bill();
	System.out.println("========object 1 created=======");
	 ref1.billRefrenceId= 1001;
	System.out.println("billRefrenceId: " +ref1.billRefrenceId);
	 ref1.billSequenceNo = 1;
	 System.out.println( "billSequenceNo: " +ref1.billSequenceNo);
     ref1.billIssueDate = "30/10/2023" ;
     System.out.println( "billIssueDate: " +ref1.billIssueDate);
	ref1.billDueDate = "29/11/2023";
	 System.out.println("billDueDate: " +ref1.billDueDate);
	ref1.isBillPaid = true;
	 System.out.println( "isBillPaid: "  +ref1.isBillPaid);
	ref1.isLatestBill=true;
	System.out.println( "isLatestBill: " +ref1.isLatestBill);
   ref1.isFinalBill=false;
	 System.out.println("isFinalBill: " +ref1.isFinalBill);
	ref1.billAmount=658.3;
	System.out.println( "billAmount: " +ref1.billAmount);
   ref1.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " +ref1.taxInculsiveBill);
		  
		
	Bill ref2 = new Bill();
	System.out.println("========object 2 created=======");
	 ref2.billRefrenceId= 1002;
	System.out.println("billRefrenceId: " +ref2.billRefrenceId);
	 ref2.billSequenceNo = 2;
	 System.out.println( "billSequenceNo: " +ref2.billSequenceNo);
     ref2.billIssueDate = "30/11/2023" ;
     System.out.println( "billIssueDate: " +ref2.billIssueDate);
	  ref2.billDueDate = "29/12/2023";
	 System.out.println("billDueDate: " +ref2.billDueDate);
     ref2.isBillPaid = true;
	 System.out.println( "isBillPaid: "  +ref2.isBillPaid);
	 ref2.isLatestBill=true;
	System.out.println( "isLatestBill: " +ref2.isLatestBill);
	 ref2.isFinalBill=false;
	 System.out.println("isFinalBill: " +ref2.isFinalBill);
	 ref2.billAmount=658.3;
	System.out.println( "billAmount: " +ref2.billAmount);
  ref2. taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " +ref2.taxInculsiveBill);
		  
		  	
	Bill ref3 = new Bill();
	System.out.println("========object 3 created=======");
	 ref3.billRefrenceId= 1003;
	System.out.println("billRefrenceId: " + ref3.billRefrenceId);
	  ref3.billSequenceNo = 3;
	 System.out.println( "billSequenceNo: " + ref3.billSequenceNo);
       ref3.billIssueDate = "30/12/2023" ;
     System.out.println( "billIssueDate: " + ref3.billIssueDate);
	   ref3.billDueDate = "29/01/2024";
	 System.out.println("billDueDate: " + ref3.billDueDate);
	  ref3.isBillPaid = true;
	 System.out.println( "isBillPaid: "  + ref3.isBillPaid);
	 ref3.isLatestBill=true;
	System.out.println( "isLatestBill: " + ref3.isLatestBill);
	  ref3.isFinalBill=false;
	 System.out.println("isFinalBill: " + ref3.isFinalBill);
	  ref3.billAmount=660.3;
	System.out.println( "billAmount: " + ref3.billAmount);
    ref3.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " + ref3.taxInculsiveBill);
   
   	
	Bill ref4 = new Bill();
	System.out.println("========object 4 created=======");
	 ref4.billRefrenceId= 1004;
	System.out.println("billRefrenceId: " + ref4.billRefrenceId);
	  ref4.billSequenceNo = 4;
	 System.out.println( "billSequenceNo: " + ref4.billSequenceNo);
      ref4.billIssueDate = "30/01/2024" ;
     System.out.println( "billIssueDate: " + ref4.billIssueDate);
	   ref4.billDueDate = "29/02/2024";
	 System.out.println("billDueDate: " + ref4.billDueDate);
	  ref4.isBillPaid = true;
	 System.out.println( "isBillPaid: "  + ref4.isBillPaid);
	 ref4.isLatestBill=true;
	System.out.println( "isLatestBill: " + ref4.isLatestBill);
	  ref4.isFinalBill=false;
	 System.out.println("isFinalBill: " + ref4.isFinalBill);
	 ref4.billAmount=658.3;
	System.out.println( "billAmount: " + ref4.billAmount);
     ref4.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " + ref4.taxInculsiveBill);
		  
		  	Bill ref5 = new Bill();
	System.out.println("========object 5 created=======");
	 ref5.billRefrenceId= 1005;
	System.out.println("billRefrenceId: " +ref5.billRefrenceId);
	 ref5.billSequenceNo = 5;
	 System.out.println( "billSequenceNo: " +ref5.billSequenceNo);
    ref5.billIssueDate = "30/02/2024" ;
     System.out.println( "billIssueDate: " +ref5.billIssueDate);
	  ref5.billDueDate = "29/03/2024";
	 System.out.println("billDueDate: " +ref5.billDueDate);
	 ref5.isBillPaid = true;
	 System.out.println( "isBillPaid: "  +ref5.isBillPaid);
	ref5.isLatestBill=true;
	System.out.println( "isLatestBill: " +ref5.isLatestBill);
	 ref5.isFinalBill=false;
	 System.out.println("isFinalBill: " +ref5.isFinalBill);
	ref5.billAmount=879.99;
	System.out.println( "billAmount: " +ref5.billAmount);
    ref5.taxInculsiveBill=false;
   System.out.println("taxInculsiveBill: " +ref5.taxInculsiveBill);
   
   	Bill ref6 = new Bill();
	System.out.println("========object 6 created=======");
	 ref6.billRefrenceId= 1006;
	System.out.println("billRefrenceId: " +ref6.billRefrenceId);
	 ref6.billSequenceNo = 6;
	 System.out.println( "billSequenceNo: " +ref6.billSequenceNo);
     ref6.billIssueDate = "30/03/2024" ;
     System.out.println( "billIssueDate: " +ref6.billIssueDate);
	  ref6.billDueDate = "29/04/2024";
	 System.out.println("billDueDate: " +ref6.billDueDate);
	 ref6.isBillPaid = true;
	 System.out.println( "isBillPaid: "  +ref6.isBillPaid);
	ref6.isLatestBill=true;
	System.out.println( "isLatestBill: " +ref6.isLatestBill);
	 ref6.isFinalBill=false;
	 System.out.println("isFinalBill: " +ref6.isFinalBill);
	ref6.billAmount=875.6;
	System.out.println( "billAmount: " +ref6.billAmount);
    ref6.taxInculsiveBill=false;
   System.out.println("taxInculsiveBill: " +ref6.taxInculsiveBill);
   
    	Bill ref7 = new Bill();
	System.out.println("========object 7 created=======");
	 ref7.billRefrenceId= 1007;
	System.out.println("billRefrenceId: " +ref7.billRefrenceId);
	 ref7.billSequenceNo = 7;
	 System.out.println( "billSequenceNo: " +ref7.billSequenceNo);
     ref7.billIssueDate = "30/04/2024" ;
     System.out.println( "billIssueDate: " +ref7.billIssueDate);
	  ref7.billDueDate = "29/05/2024";
	 System.out.println("billDueDate: " +ref7.billDueDate);
	 ref7.isBillPaid = true;
	 System.out.println( "isBillPaid: "  +ref7.isBillPaid);
	ref7.isLatestBill=true;
	System.out.println( "isLatestBill: " +ref7.isLatestBill);
	 ref7.isFinalBill=false;
	 System.out.println("isFinalBill: " +ref7.isFinalBill);
	ref7.billAmount=879.6;
	System.out.println( "billAmount: " +ref7.billAmount);
    ref7.taxInculsiveBill=false;
   System.out.println("taxInculsiveBill: " +ref7.taxInculsiveBill);
   
    	Bill ref8 = new Bill();
	System.out.println("========object 8 created=======");
	 ref8.billRefrenceId= 1008;
	System.out.println("billRefrenceId: " + ref8.billRefrenceId);
	  ref8.billSequenceNo = 8;
	 System.out.println( "billSequenceNo: " + ref8.billSequenceNo);
      ref8.billIssueDate = "30/03/2024" ;
     System.out.println( "billIssueDate: " + ref8.billIssueDate);
	   ref8.billDueDate = "29/04/2024";
	 System.out.println("billDueDate: " + ref8.billDueDate);
	  ref8.isBillPaid = true;
	 System.out.println( "isBillPaid: "  + ref8.isBillPaid);
	 ref8.isLatestBill=true;
	System.out.println( "isLatestBill: " + ref8.isLatestBill);
	  ref8.isFinalBill=false;
	 System.out.println("isFinalBill: " + ref8.isFinalBill);
	 ref8.billAmount=875.6;
	System.out.println( "billAmount: " + ref8.billAmount);
     ref8.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " + ref8.taxInculsiveBill);
		  
		   	Bill ref9 = new Bill();
	System.out.println("========object 9 created=======");
	 ref9.billRefrenceId= 1009;
	System.out.println("billRefrenceId: " + ref9.billRefrenceId);
	  ref9.billSequenceNo = 9;
	 System.out.println( "billSequenceNo: " + ref9.billSequenceNo);
      ref9.billIssueDate = "30/05/2024" ;
     System.out.println( "billIssueDate: " + ref9.billIssueDate);
	   ref9.billDueDate = "29/06/2024";
	 System.out.println("billDueDate: " + ref9.billDueDate);
	 ref9.isBillPaid = true;
	 System.out.println( "isBillPaid: "  + ref9.isBillPaid);
	 ref9.isLatestBill=true;
	System.out.println( "isLatestBill: " + ref9.isLatestBill);
	  ref9.isFinalBill=false;
	 System.out.println("isFinalBill: " + ref9.isFinalBill);
	ref9.billAmount=999.99;
	System.out.println( "billAmount: " + ref9.billAmount);
     ref9.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " + ref9.taxInculsiveBill);
   
    	Bill ref10 = new Bill();
	System.out.println("========object 10 created=======");
	 ref10.billRefrenceId= 1010;
	System.out.println("billRefrenceId: " + ref10.billRefrenceId);
	  ref10.billSequenceNo = 10;
	 System.out.println( "billSequenceNo: " + ref10.billSequenceNo);
      ref10.billIssueDate = "30/06/2024" ;
     System.out.println( "billIssueDate: " + ref10.billIssueDate);
	   ref10.billDueDate = "29/07/2024";
	 System.out.println("billDueDate: " + ref10.billDueDate);
	  ref10.isBillPaid = true;
	 System.out.println( "isBillPaid: "  + ref10.isBillPaid);
	 ref10.isLatestBill=true;
	System.out.println( "isLatestBill: " + ref10.isLatestBill);
	  ref10.isFinalBill=true;
	 System.out.println("isFinalBill: " + ref10.isFinalBill);
	 ref10.billAmount=875.6;
	System.out.println( "billAmount: " + ref10.billAmount);
     ref10.taxInculsiveBill=true;
   System.out.println("taxInculsiveBill: " + ref10.taxInculsiveBill);
}
}