class BillRunner{

public static void main(String[] args){
	
	
	Bill ref1 = new Bill();
	System.out.println("========object 1 created=======");
	int billRefrenceId= 1001;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 int billSequenceNo = 1;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     String billIssueDate = "30/10/2023" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	 String billDueDate = "29/11/2023";
	 System.out.println("billDueDate: " +billDueDate);
	boolean isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	boolean isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	boolean isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	double billAmount=658.3;
	System.out.println( "billAmount: " +billAmount);
   double taxInculsiveBill=50.4;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
		  
		
	Bill ref2 = new Bill();
	System.out.println("========object 2 created=======");
	 billRefrenceId= 1002;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 2;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/11/2023" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/12/2023";
	 System.out.println("billDueDate: " +billDueDate);
     isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	 isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	 billAmount=658.3;
	System.out.println( "billAmount: " +billAmount);
   taxInculsiveBill=50.3;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
		  
		  	
	Bill ref3 = new Bill();
	System.out.println("========object 3 created=======");
	 billRefrenceId= 1003;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 3;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
      billIssueDate = "30/12/2023" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/01/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	 billAmount=660.3;
	System.out.println( "billAmount: " +billAmount);
   taxInculsiveBill=50.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
   
   	
	Bill ref4 = new Bill();
	System.out.println("========object 4 created=======");
	 billRefrenceId= 1004;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 4;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/01/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/02/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=658.3;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=50.4;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
		  
		  	Bill ref5 = new Bill();
	System.out.println("========object 5 created=======");
	 billRefrenceId= 1005;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 5;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/02/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/03/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=879.99;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=68.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
   
   	Bill ref6 = new Bill();
	System.out.println("========object 6 created=======");
	 billRefrenceId= 1006;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 6;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/03/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/04/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=875.6;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=70.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
   
    	Bill ref7 = new Bill();
	System.out.println("========object 7 created=======");
	 billRefrenceId= 1007;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 7;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/04/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/05/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=879.6;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=70.4;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
   
    	Bill ref8 = new Bill();
	System.out.println("========object 8 created=======");
	 billRefrenceId= 1008;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 8;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/03/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/04/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=875.6;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=70.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
		  
		   	Bill ref9 = new Bill();
	System.out.println("========object 9 created=======");
	 billRefrenceId= 1009;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 9;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/05/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/06/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=false;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=999.99;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=80.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
   
    	Bill ref10 = new Bill();
	System.out.println("========object 10 created=======");
	 billRefrenceId= 1010;
	System.out.println("billRefrenceId: " +billRefrenceId);
	 billSequenceNo = 10;
	 System.out.println( "billSequenceNo: " +billSequenceNo);
     billIssueDate = "30/06/2024" ;
     System.out.println( "billIssueDate: " +billIssueDate);
	  billDueDate = "29/07/2024";
	 System.out.println("billDueDate: " +billDueDate);
	 isBillPaid = true;
	 System.out.println( "isBillPaid: "  +isBillPaid);
	isLatestBill=true;
	System.out.println( "isLatestBill: " +isLatestBill);
	 isFinalBill=true;
	 System.out.println("isFinalBill: " +isFinalBill);
	billAmount=875.6;
	System.out.println( "billAmount: " +billAmount);
    taxInculsiveBill=70.9;
   System.out.println("taxInculsiveBill: " +taxInculsiveBill);
}
}